spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
server:
  port: 7902
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000